version: '3'
services:
  ml-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python3 src/deployment/app.py
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - ml-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
